all: decoder.exe

decoder.exe: decoder.c ../src/vgs2tone.c ../src/vgsdec.c
	CL /MT -I../src decoder.c ../src/vgs2tone.c ../src/vgsdec.c ws2_32.lib

test: decoder.exe
	vgs2mml test.mml test.bgm
	.\decoder test.bgm test.wav

